/// Generated by AssetsRefGenerator on 2022/05/30
class Res {
  static const String app_icon = "assets/images/app_icon.png";
  static const String banner = "assets/images/banner.jpg";
  static const String bottle = "assets/images/bottle.png";
  static const String chirz_video = "assets/chirz_video.mp4";
  static const String cocktail = "assets/images/cocktail.png";
  static const String cocktail1 = "assets/images/cocktail1.jpg";
  static const String food_static = "assets/images/food_static.png";
  static const String glass = "assets/images/glass.png";
  static const String londin = "assets/images/londin.jpg";
  static const String order_successfully = "assets/images/order_successfully.png";
  static const String poppins_bold = "assets/fonts/poppins_bold.ttf";
  static const String poppins_semibold = "assets/fonts/poppins_semibold.ttf";
  static const String poppinsregular = "assets/fonts/poppinsregular.ttf";
  static const String profile_pic_placeholder = "assets/images/profile_pic_placeholder.png";
  static const String splash = "assets/images/splash.jpg";
  static const String tasking = "assets/images/tasking.jpg";
  static const String wine = "assets/images/wine.jpg";
  static const String wine1 = "assets/images/wine1.jpeg";
  static const String wine2 = "assets/images/wine2.jpeg";
  static const String wine3 = "assets/images/wine3.jpeg";
}
